[workspace]
members = [
    ".",
    "fuzz",
]

[package]
name = "ekv"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = { version = "0.3.2", optional = true }
heapless = "0.7.16"
log = { version = "0.4.17", optional = true }
rand = "0.8.5"
